### ISSUE TITLE
Update Garden Linux features/*/info.yaml files, so that layers, their mediatypes and annotations are defined

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/python-gardenlinux-lib#16]
## Requirements

- All Garden Linux feature info.yaml files must be extended to include information about build artifacts so that they can be added to the oci-image as a layer

## Notes
- The issues (#8, and https://github.com/gardenlinux/parse_features_lib/issues/1) are strongly related to this issue, and should be developed alongside this issue
- Not all features generate new build artifacts
- root filesystem mediatype is different for different features
- Please re-use existing mediatypes if possible 
- Start with a small set of features then request review before continuing with more features
    - metal: https://github.com/gardenlinux/gardenlinux/blob/main/features/metal/info.yaml
    - and all recursively included features by metal 

## Example 
```
description:  "Example Data for gl-oci"
type: platform
features:
  include:
    - cloud
oci_artifacts:
    - file_name: foo.bar
      media_type: application/vnd.oci.image.layer.v1.tar+gzip
      annotations:
        org.opencontainers.image.title: "Just some example Data"
        org.opencontainers.image.decription: "Just some example Data desc"
    - file_name: test.log
      media_type: application/vnd.oci.image.layer.v1.tar+gzip
      annotations:
        org.opencontainers.image.title: "Example Test log"
        org.opencontainers.image.description: "Example Test log desc"
```
